# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "samorab-${version}";
  version = "2017-10-19";
  rev = "1cc3876a7f0d74244cec7ae84d1c922c3e0d8c29";

  goPackagePath = "github.com/pltanton/samorab";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/pltanton/samorab";
    sha256 = "0mbj8m5x9rl32ha23hz6rn6jjmx4saqafipyr3yxc46zw8k4lb3i";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
