# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/boltdb/bolt";
    fetch = {
      type = "git";
      url = "https://github.com/boltdb/bolt";
      rev = "fd01fc79c553a8e99d512a07e8e0c63d4a3ccfc5";
      sha256 = "12f5swiwzcamk87r9j73nn7rmyyday7jkgzfh7x5wdg9blzhrir2";
    };
  }
  {
    goPackagePath = "github.com/olebedev/config";
    fetch = {
      type = "git";
      url = "https://github.com/olebedev/config";
      rev = "57f804269e64d41bfe46efb76232c47f49d40902";
      sha256 = "1vq1m1y10i8nisns5pxxgf05vzg89s7vf71arafcp12jsri2srap";
    };
  }
  {
    goPackagePath = "github.com/technoweenie/multipartstreamer";
    fetch = {
      type = "git";
      url = "https://github.com/technoweenie/multipartstreamer";
      rev = "a90a01d73ae432e2611d178c18367fbaa13e0154";
      sha256 = "159jhcabdkds8m5777zfs8p5z3snpjhzz7q9aq9wjpcvh6xlljqa";
    };
  }
  {
    goPackagePath = "github.com/un000/mystem-wrapper";
    fetch = {
      type = "git";
      url = "https://github.com/un000/mystem-wrapper";
      rev = "eb938ea4280853f91340788e233ed29ebb346b73";
      sha256 = "0l0ql2qnq2p0zzxslq4s5w6p739b9gvhgkz82ryadg1hk2nk8rpc";
    };
  }
  {
    goPackagePath = "gopkg.in/telegram-bot-api.v4";
    fetch = {
      type = "git";
      url = "https://gopkg.in/telegram-bot-api.v4";
      rev = "9860bdfd3a171ceafb6e1eafa163482a6ef92643";
      sha256 = "1x6j0k3aiicsr8l53na99ci10zm3qpn2syz4f60fzh164w5k1l7w";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "51d6538a90f86fe93ac480b35f37b2be17fef232";
      sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa";
    };
  }
]
